export const AUTHORITY_OPTIONS: Record<string, string[]> = {
  jobcenter: [
    'Jobcenter Berlin Mitte',
    'Jobcenter Berlin Neukölln',
    'Jobcenter Berlin Tempelhof-Schöneberg',
    'Jobcenter Berlin Charlottenburg-Wilmersdorf',
    'Jobcenter München',
    'Jobcenter Hamburg',
    'Jobcenter Köln',
    'Jobcenter Frankfurt am Main',
    'Jobcenter Stuttgart',
    'Jobcenter Düsseldorf',
    'Jobcenter Dortmund',
    'Jobcenter Essen',
    'Jobcenter Bremen',
    'Jobcenter Hannover',
    'Jobcenter Nürnberg',
    'Jobcenter Leipzig',
    'Jobcenter Dresden',
    'Jobcenter Bochum',
    'Jobcenter Herne',
    'Jobcenter Duisburg',
    'Jobcenter Gelsenkirchen',
    'Jobcenter Bielefeld',
    'Jobcenter Mannheim',
    'Jobcenter Wuppertal',
  ],
  auslaenderbehoerde: [
    'Landesamt für Einwanderung Berlin (LEA)',
    'Ausländerbehörde München',
    'Ausländerbehörde Hamburg',
    'Ausländerbehörde Köln',
    'Ausländerbehörde Frankfurt am Main',
    'Ausländerbehörde Stuttgart',
    'Ausländerbehörde Düsseldorf',
    'Ausländerbehörde Dortmund',
    'Ausländerbehörde Essen',
    'Ausländerbehörde Bremen',
    'Ausländerbehörde Hannover',
    'Ausländerbehörde Nürnberg',
    'Ausländerbehörde Leipzig',
    'Ausländerbehörde Dresden',
    'Ausländerbehörde Bochum',
    'Ausländerbehörde Herne',
    'Ausländerbehörde Duisburg',
    'Ausländerbehörde Mannheim',
  ],
  finanzamt: [
    'Finanzamt Berlin Mitte/Tiergarten',
    'Finanzamt Berlin Neukölln',
    'Finanzamt Berlin Charlottenburg',
    'Finanzamt München I',
    'Finanzamt München II',
    'Finanzamt Hamburg-Mitte',
    'Finanzamt Köln-Mitte',
    'Finanzamt Frankfurt am Main I',
    'Finanzamt Stuttgart I',
    'Finanzamt Düsseldorf-Mitte',
    'Finanzamt Dortmund-Ost',
    'Finanzamt Essen-Süd',
    'Finanzamt Bremen',
    'Finanzamt Hannover-Mitte',
    'Finanzamt Nürnberg-Zentral',
    'Finanzamt Herne',
  ],
  krankenkasse: [
    'AOK – Die Gesundheitskasse',
    'AOK Bayern',
    'AOK Nordost',
    'AOK Baden-Württemberg',
    'AOK Rheinland/Hamburg',
    'Techniker Krankenkasse (TK)',
    'BARMER',
    'DAK-Gesundheit',
    'IKK classic',
    'IKK gesund plus',
    'KKH Kaufmännische Krankenkasse',
    'HEK – Hanseatische Krankenkasse',
    'hkk Krankenkasse',
    'Knappschaft',
    'BKK Mobil Oil',
  ],
  versicherung: [
    'Allianz Versicherung',
    'HUK-COBURG',
    'ERGO Versicherung',
    'AXA Versicherung',
    'Generali Deutschland',
    'Zurich Versicherung',
    'HDI Versicherung',
    'R+V Versicherung',
    'Debeka Versicherung',
    'DEVK Versicherung',
    'Gothaer Versicherung',
    'Württembergische Versicherung',
    'VHV Versicherung',
    'Haftpflichtkasse',
  ],
  familienkasse: [
    'Familienkasse Berlin-Brandenburg',
    'Familienkasse Bayern Süd',
    'Familienkasse Bayern Nord',
    'Familienkasse Hamburg',
    'Familienkasse Nordrhein-Westfalen Nord',
    'Familienkasse Nordrhein-Westfalen West',
    'Familienkasse Hessen',
    'Familienkasse Baden-Württemberg West',
    'Familienkasse Baden-Württemberg Ost',
    'Familienkasse Niedersachsen-Bremen',
    'Familienkasse Sachsen',
    'Familienkasse Nord',
  ],
  bamf: [
    'BAMF – Außenstelle Berlin',
    'BAMF – Außenstelle München',
    'BAMF – Außenstelle Hamburg',
    'BAMF – Außenstelle Köln',
    'BAMF – Außenstelle Frankfurt',
    'BAMF – Außenstelle Düsseldorf',
    'BAMF – Außenstelle Dortmund',
    'BAMF – Außenstelle Nürnberg (Zentrale)',
    'BAMF – Außenstelle Bremen',
    'BAMF – Außenstelle Hannover',
    'BAMF – Außenstelle Stuttgart',
    'BAMF – Außenstelle Leipzig',
    'BAMF – Außenstelle Dresden',
  ],
  buergeramt: [
    'Bürgeramt Berlin Mitte',
    'Bürgeramt Berlin Neukölln',
    'Bürgeramt Berlin Tempelhof-Schöneberg',
    'Bürgerbüro München',
    'Kundenzentrum Hamburg',
    'Bürgeramt Köln',
    'Bürgeramt Frankfurt am Main',
    'Bürgerbüro Stuttgart',
    'Bürgerbüro Düsseldorf',
    'Bürgerdienste Dortmund',
    'Bürgerdienste Essen',
    'Bürgeramt Hannover',
    'Bürgeramt Leipzig',
    'Bürgeramt Bremen',
    'Bürgeramt Herne',
  ],
  rentenversicherung: [
    'Deutsche Rentenversicherung Bund',
    'Deutsche Rentenversicherung Berlin-Brandenburg',
    'Deutsche Rentenversicherung Bayern Süd',
    'Deutsche Rentenversicherung Nord',
    'Deutsche Rentenversicherung Rheinland',
    'Deutsche Rentenversicherung Westfalen',
    'Deutsche Rentenversicherung Hessen',
    'Deutsche Rentenversicherung Baden-Württemberg',
    'Deutsche Rentenversicherung Mitteldeutschland',
    'Deutsche Rentenversicherung Braunschweig-Hannover',
    'Deutsche Rentenversicherung Knappschaft-Bahn-See',
  ],
};

export const NATIONALITY_OPTIONS = [
  'Türkisch',
  'Syrisch',
  'Afghanisch',
  'Irakisch',
  'Iranisch',
  'Aserbaidschanisch',
  'Russisch',
  'Ukrainisch',
  'Polnisch',
  'Rumänisch',
  'Bulgarisch',
  'Kroatisch',
  'Serbisch',
  'Bosnisch-herzegowinisch',
  'Kosovarisch',
  'Albanisch',
  'Griechisch',
  'Italienisch',
  'Spanisch',
  'Portugiesisch',
  'Marokkanisch',
  'Tunesisch',
  'Ägyptisch',
  'Indisch',
  'Pakistanisch',
  'Eritreisch',
  'Somalisch',
  'Nigerianisch',
  'Georgisch',
  'Armenisch',
  'Vietnamesisch',
  'Chinesisch',
  'Brasilianisch',
  'Kolumbianisch',
  'Amerikanisch',
  'Britisch',
  'Französisch',
];
