-- Şablon kategorilerini ekle
INSERT INTO template_categories (slug, name, description, icon) VALUES
  ('jobcenter', '{"de":"Jobcenter","tr":"Jobcenter","en":"Job Center","az":"Jobcenter","ru":"Центр занятости","uk":"Центр зайнятості","ar":"مركز التوظيف"}', '{"de":"Jobcenter Vorlagen","tr":"Jobcenter şablonları","en":"Job Center templates","az":"Jobcenter şablonları","ru":"Шаблоны центра занятости","uk":"Шаблони центру зайнятості","ar":"قوالب مركز التوظيف"}', 'briefcase'),
  ('auslaenderbehoerde', '{"de":"Ausländerbehörde","tr":"Yabancılar Dairesi","en":"Immigration Office","az":"Əcnəbilər İdarəsi","ru":"Ведомство по делам иностранцев","uk":"Управління у справах іноземців","ar":"مكتب الأجانب"}', '{"de":"Ausländerbehörde Vorlagen","tr":"Yabancılar Dairesi şablonları","en":"Immigration Office templates","az":"Əcnəbilər İdarəsi şablonları","ru":"Шаблоны ведомства по делам иностранцев","uk":"Шаблони управління у справах іноземців","ar":"قوالب مكتب الأجانب"}', 'globe'),
  ('finanzamt', '{"de":"Finanzamt","tr":"Vergi Dairesi","en":"Tax Office","az":"Vergi İdarəsi","ru":"Налоговая инспекция","uk":"Податкова інспекція","ar":"مصلحة الضرائب"}', '{"de":"Finanzamt Vorlagen","tr":"Vergi Dairesi şablonları","en":"Tax Office templates","az":"Vergi İdarəsi şablonları","ru":"Шаблоны налоговой инспекции","uk":"Шаблони податкової інспекції","ar":"قوالب مصلحة الضرائب"}', 'calculator'),
  ('krankenkasse', '{"de":"Krankenkasse","tr":"Sağlık Sigortası","en":"Health Insurance","az":"Tibbi Sığorta","ru":"Медицинское страхование","uk":"Медичне страхування","ar":"التأمين الصحي"}', '{"de":"Krankenkasse Vorlagen","tr":"Sağlık Sigortası şablonları","en":"Health Insurance templates","az":"Tibbi Sığorta şablonları","ru":"Шаблоны медицинского страхования","uk":"Шаблони медичного страхування","ar":"قوالب التأمين الصحي"}', 'heart-pulse'),
  ('wohnung', '{"de":"Wohnung","tr":"Konut","en":"Housing","az":"Mənzil","ru":"Жильё","uk":"Житло","ar":"السكن"}', '{"de":"Wohnungs Vorlagen","tr":"Konut şablonları","en":"Housing templates","az":"Mənzil şablonları","ru":"Шаблоны жилья","uk":"Шаблони житла","ar":"قوالب السكن"}', 'home'),
  ('versicherung', '{"de":"Versicherung","tr":"Sigorta","en":"Insurance","az":"Sığorta","ru":"Страхование","uk":"Страхування","ar":"التأمين"}', '{"de":"Versicherungs Vorlagen","tr":"Sigorta şablonları","en":"Insurance templates","az":"Sığorta şablonları","ru":"Шаблоны страхования","uk":"Шаблони страхування","ar":"قوالب التأمين"}', 'shield'),
  ('schule', '{"de":"Schule/Kita","tr":"Okul/Kreş","en":"School/Daycare","az":"Məktəb/Uşaq bağçası","ru":"Школа/Детский сад","uk":"Школа/Дитячий садок","ar":"المدرسة/الحضانة"}', '{"de":"Schule/Kita Vorlagen","tr":"Okul/Kreş şablonları","en":"School/Daycare templates","az":"Məktəb/Uşaq bağçası şablonları","ru":"Шаблоны школы/детского сада","uk":"Шаблони школи/дитячого садка","ar":"قوالب المدرسة/الحضانة"}', 'graduation-cap'),
  ('allgemein', '{"de":"Allgemein","tr":"Genel","en":"General","az":"Ümumi","ru":"Общее","uk":"Загальне","ar":"عام"}', '{"de":"Allgemeine Vorlagen","tr":"Genel şablonlar","en":"General templates","az":"Ümumi şablonlar","ru":"Общие шаблоны","uk":"Загальні шаблони","ar":"قوالب عامة"}', 'file-text')
ON CONFLICT (slug) DO NOTHING;
